# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_VERSION = 160

BOARD_TAG    = uno

AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
ARDUINO_LIB_PATH = /usr/share/arduino/hardware/arduino/libraries
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders

USER_LIB_PATH = libraries
ARDUINO_LIBS = Servo PulseInZero PinChangeInt

ARDUINO_PORT = /dev/ttyUSB0

CPPFLAGS = -std=c++11
OPTIMIZATION_LEVEL = 2

include /usr/share/arduino/Arduino.mk

